[package]

name = "capnp-rpc"
version = "0.6.0-dev"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnp-rpc-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies.capnpc]
git = "https://github.com/dwrensha/capnpc-rust"

[dependencies]
gj = "*"

[dependencies.capnp]
git = "https://github.com/dwrensha/capnproto-rust"
path = "../capnproto-rust"
features = ["rpc"]

[dependencies.capnp-gj]
git = "https://github.com/dwrensha/capnp-gj"


