[package]

name = "capnp-rpc"
version = "0.0.1"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "Experimental Cap'n Proto RPC layer"

[lib]

name = "capnp-rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.0.1"

[dependencies]
capnp = "0.0.1"
