[package]

name = "capnp-rpc"
version = "0.1.20"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "Experimental Cap'n Proto RPC layer"
repository = "https://github.com/dwrensha/capnp-rpc-rust"
documentation = "http://docs.capnproto-rust.org"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.1.27"

[dependencies]
capnp = "0.1.27"
