[package]

name = "capnp-rpc"
version = "0.1.0"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]
build = "make generated"

[lib]

name = "capnp-rpc"
path = "src/lib.rs"


[dependencies.capnp]

git = "https://github.com/dwrensha/capnproto-rust.git"