[package]

name = "capnp-rpc"
version = "0.6.3"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>" ]
build = "build.rs"
license = "MIT"
description = "implementation of the Cap'n Proto remote procedure call protocol"
repository = "https://github.com/dwrensha/capnp-rpc-rust"
documentation = "http://docs.capnproto-rust.org/capnp_rpc/"

[lib]

name = "capnp_rpc"
path = "src/lib.rs"

[build-dependencies]
capnpc = "0.6"

[dependencies]
gj = "0.1"
capnp = {version = "0.6.2", features = ["rpc"]}
capnp-gj = "0.1"

[dependencies.gjio]
git = "https://github.com/dwrensha/gjio.git"



