[package]

name = "calculator"
version = "0.0.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>"  ]
build = "build.rs"

[[bin]]

name = "calculator"
path = "main.rs"

[build-dependencies.capnpc]
git = "https://github.com/dwrensha/capnpc-rust"

[dependencies]
gj = "*"

[dependencies.capnp-rpc]
path = "../.."

[dependencies.capnp]
git = "https://github.com/dwrensha/capnproto-rust"