[package]

name = "calculator"
version = "0.0.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>"  ]
build = "build.rs"

[profile.dev]
debug = false

[[bin]]

name = "calculator"
path = "main.rs"

[build-dependencies]
capnpc = "0.1.5"

[dependencies]
capnp = "0.1.4"

[dependencies.capnp-rpc]
path = "../.."